ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ4MjUxMzQyLjE3NDYxODMxNjQifSwiYW5vbklkIjoiNTkwMTY2YTE0OTVmNjJiMSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5hdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNzEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyMzg2MTUwNTQ3ODUxNjI3NiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55903cab775a <unknown>
#1 0x55903c56a4b0 <unknown>
#2 0x55903c550d86 <unknown>
#3 0x55903c54f69a <unknown>
#4 0x55903c54fdff <unknown>
#5 0x55903c54fd54 <unknown>
#6 0x55903c56e69f <unknown>
#7 0x55903c61392a <unknown>
#8 0x55903c5e1592 <unknown>
#9 0x55903c6075e0 <unknown>
#10 0x55903c5e1363 <unknown>
#11 0x55903c5add63 <unknown>
#12 0x55903c5ae9c1 <unknown>
#13 0x55903ca7ca6b <unknown>
#14 0x55903ca80951 <unknown>
#15 0x55903ca64b62 <unknown>
#16 0x55903ca814c4 <unknown>
#17 0x55903ca4913f <unknown>
#18 0x55903caa56f8 <unknown>
#19 0x55903caa58d6 <unknown>
#20 0x55903cab65a6 <unknown>
#21 0x7fb92a29caa4 <unknown>
#22 0x7fb92a329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJkZV9BVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI3MSJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ4MjUxMzQyLjE3NDYxODMxNjQifSwiYW5vbklkIjoiNTkwMTY2YTE0OTVmNjJiMSJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMzYzIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMzYzIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTcyNjUwNTUzNjMyOTY3NSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55903cab775a <unknown>
#1 0x55903c56a4b0 <unknown>
#2 0x55903c550d86 <unknown>
#3 0x55903c54f69a <unknown>
#4 0x55903c54fdff <unknown>
#5 0x55903c54fd54 <unknown>
#6 0x55903c56e69f <unknown>
#7 0x55903c61392a <unknown>
#8 0x55903c5e1592 <unknown>
#9 0x55903c6075e0 <unknown>
#10 0x55903c5e1363 <unknown>
#11 0x55903c5add63 <unknown>
#12 0x55903c5ae9c1 <unknown>
#13 0x55903ca7ca6b <unknown>
#14 0x55903ca80951 <unknown>
#15 0x55903ca64b62 <unknown>
#16 0x55903ca814c4 <unknown>
#17 0x55903ca4913f <unknown>
#18 0x55903caa56f8 <unknown>
#19 0x55903caa58d6 <unknown>
#20 0x55903cab65a6 <unknown>
#21 0x7fb92a29caa4 <unknown>
#22 0x7fb92a329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0ODI1MTM0Mi4xNzQ2MTgzMTY0In0sImFub25JZCI6IjU5MDE2NmExNDk1ZjYyYjEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjcxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjQ5MzE0ODE0NjUyNjg4NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55903cab775a <unknown>
#1 0x55903c56a4b0 <unknown>
#2 0x55903c550d86 <unknown>
#3 0x55903c54f69a <unknown>
#4 0x55903c54fdff <unknown>
#5 0x55903c54fd54 <unknown>
#6 0x55903c56e69f <unknown>
#7 0x55903c61392a <unknown>
#8 0x55903c5e1592 <unknown>
#9 0x55903c6075e0 <unknown>
#10 0x55903c5e1363 <unknown>
#11 0x55903c5add63 <unknown>
#12 0x55903c5ae9c1 <unknown>
#13 0x55903ca7ca6b <unknown>
#14 0x55903ca80951 <unknown>
#15 0x55903ca64b62 <unknown>
#16 0x55903ca814c4 <unknown>
#17 0x55903ca4913f <unknown>
#18 0x55903caa56f8 <unknown>
#19 0x55903caa58d6 <unknown>
#20 0x55903cab65a6 <unknown>
#21 0x7fb92a29caa4 <unknown>
#22 0x7fb92a329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Perso/QA-Perso/Tests/BFV1_attempt_2.png'