ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f6bb4087fa <unknown>
#1 0x55f6baeace90 <unknown>
#2 0x55f6baefe870 <unknown>
#3 0x55f6baefea91 <unknown>
#4 0x55f6baef2446 <unknown>
#5 0x55f6baf2426d <unknown>
#6 0x55f6baef22fa <unknown>
#7 0x55f6baf2440e <unknown>
#8 0x55f6baf4a135 <unknown>
#9 0x55f6baf24013 <unknown>
#10 0x55f6baef0b3b <unknown>
#11 0x55f6baef17a1 <unknown>
#12 0x55f6bb3cdb9b <unknown>
#13 0x55f6bb3d1a8a <unknown>
#14 0x55f6bb3b5912 <unknown>
#15 0x55f6bb3d2604 <unknown>
#16 0x55f6bb39a74f <unknown>
#17 0x55f6bb3f6678 <unknown>
#18 0x55f6bb3f6856 <unknown>
#19 0x55f6bb407666 <unknown>
#20 0x7f02c829caa4 <unknown>
#21 0x7f02c8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_denmark_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGFfREsiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmRrL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9ESy9kYS9ibS80NjUyMTAxLDQ2NTI1MDEsNDY1MzEwMT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNjU1OTQ0NDc0LjE3NDcxMjg5NTcifSwiYW5vbklkIjoiZjcxYjYxMmMxZmZiODdkZCJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjcyNzUzODQ3OTI1ODQyMDIifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f6bb4087fa <unknown>
#1 0x55f6baeace90 <unknown>
#2 0x55f6bae94156 <unknown>
#3 0x55f6bae92a6a <unknown>
#4 0x55f6bae931cf <unknown>
#5 0x55f6bae93124 <unknown>
#6 0x55f6baeb111f <unknown>
#7 0x55f6baf563ca <unknown>
#8 0x55f6baf24242 <unknown>
#9 0x55f6baf4a135 <unknown>
#10 0x55f6baf24013 <unknown>
#11 0x55f6baef0b3b <unknown>
#12 0x55f6baef17a1 <unknown>
#13 0x55f6bb3cdb9b <unknown>
#14 0x55f6bb3d1a8a <unknown>
#15 0x55f6bb3b5912 <unknown>
#16 0x55f6bb3d2604 <unknown>
#17 0x55f6bb39a74f <unknown>
#18 0x55f6bb3f6678 <unknown>
#19 0x55f6bb3f6856 <unknown>
#20 0x55f6bb407666 <unknown>
#21 0x7f02c829caa4 <unknown>
#22 0x7f02c8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_denmark_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTY1NTk0NDQ3NC4xNzQ3MTI4OTU3In0sImFub25JZCI6ImY3MWI2MTJjMWZmYjg3ZGQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouZGsvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0RLL2RhL2JtLzQ2NTIxMDEsNDY1MjUwMSw0NjUzMTAxP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjUiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoyfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwMzIxNDkyMjk0MTc5MTE0MyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f6bb4087fa <unknown>
#1 0x55f6baeace90 <unknown>
#2 0x55f6bae94156 <unknown>
#3 0x55f6bae92a6a <unknown>
#4 0x55f6bae931cf <unknown>
#5 0x55f6bae93124 <unknown>
#6 0x55f6baeb111f <unknown>
#7 0x55f6baf563ca <unknown>
#8 0x55f6baf24242 <unknown>
#9 0x55f6baf4a135 <unknown>
#10 0x55f6baf24013 <unknown>
#11 0x55f6baef0b3b <unknown>
#12 0x55f6baef17a1 <unknown>
#13 0x55f6bb3cdb9b <unknown>
#14 0x55f6bb3d1a8a <unknown>
#15 0x55f6bb3b5912 <unknown>
#16 0x55f6bb3d2604 <unknown>
#17 0x55f6bb39a74f <unknown>
#18 0x55f6bb3f6678 <unknown>
#19 0x55f6bb3f6856 <unknown>
#20 0x55f6bb407666 <unknown>
#21 0x7f02c829caa4 <unknown>
#22 0x7f02c8329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: