ERROR    root:ConfigStarted.py:40 ❌ Error in configurator: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55ff21df375a <unknown>
#1 0x55ff218a64b0 <unknown>
#2 0x55ff218f79b3 <unknown>
#3 0x55ff218f7bd1 <unknown>
#4 0x55ff218eb4b6 <unknown>
#5 0x55ff2191d5bd <unknown>
#6 0x55ff218eb36a <unknown>
#7 0x55ff2191d75e <unknown>
#8 0x55ff219435e0 <unknown>
#9 0x55ff2191d363 <unknown>
#10 0x55ff218e9d63 <unknown>
#11 0x55ff218ea9c1 <unknown>
#12 0x55ff21db8a6b <unknown>
#13 0x55ff21dbc951 <unknown>
#14 0x55ff21da0b62 <unknown>
#15 0x55ff21dbd4c4 <unknown>
#16 0x55ff21d8513f <unknown>
#17 0x55ff21de16f8 <unknown>
#18 0x55ff21de18d6 <unknown>
#19 0x55ff21df25a6 <unknown>
#20 0x7f522d29caa4 <unknown>
#21 0x7f522d329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_belgium_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoibmxfQkUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmJlL25sX0JFL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9CRS9ubC9DLUtMQVNTRS9MSU1PVVNJTkUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjI0MSJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYzNzM2NjAuMTc0NjM0Mjg2MyJ9LCJhbm9uSWQiOiJkM2RkZGRkNjQzMmU3M2QzIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzA4Mjc5Nzc3NjQxNjg5MjMifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55ff21df375a <unknown>
#1 0x55ff218a64b0 <unknown>
#2 0x55ff2188cd86 <unknown>
#3 0x55ff2188b69a <unknown>
#4 0x55ff2188bdff <unknown>
#5 0x55ff2188bd54 <unknown>
#6 0x55ff218aa69f <unknown>
#7 0x55ff2194f92a <unknown>
#8 0x55ff2191d592 <unknown>
#9 0x55ff219435e0 <unknown>
#10 0x55ff2191d363 <unknown>
#11 0x55ff218e9d63 <unknown>
#12 0x55ff218ea9c1 <unknown>
#13 0x55ff21db8a6b <unknown>
#14 0x55ff21dbc951 <unknown>
#15 0x55ff21da0b62 <unknown>
#16 0x55ff21dbd4c4 <unknown>
#17 0x55ff21d8513f <unknown>
#18 0x55ff21de16f8 <unknown>
#19 0x55ff21de18d6 <unknown>
#20 0x55ff21df25a6 <unknown>
#21 0x7f522d29caa4 <unknown>
#22 0x7f522d329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_belgium_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYzNzM2NjAuMTc0NjM0Mjg2MyJ9LCJhbm9uSWQiOiJkM2RkZGRkNjQzMmU3M2QzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmJlL25sX0JFL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9CRS9ubC9DLUtMQVNTRS9MSU1PVVNJTkUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjI0MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU2ODAyMzYzNjg0NzI2MjgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55ff21df375a <unknown>
#1 0x55ff218a64b0 <unknown>
#2 0x55ff2188cd86 <unknown>
#3 0x55ff2188b69a <unknown>
#4 0x55ff2188bdff <unknown>
#5 0x55ff2188bd54 <unknown>
#6 0x55ff218aa69f <unknown>
#7 0x55ff2194f92a <unknown>
#8 0x55ff2191d592 <unknown>
#9 0x55ff219435e0 <unknown>
#10 0x55ff2191d363 <unknown>
#11 0x55ff218e9d63 <unknown>
#12 0x55ff218ea9c1 <unknown>
#13 0x55ff21db8a6b <unknown>
#14 0x55ff21dbc951 <unknown>
#15 0x55ff21da0b62 <unknown>
#16 0x55ff21dbd4c4 <unknown>
#17 0x55ff21d8513f <unknown>
#18 0x55ff21de16f8 <unknown>
#19 0x55ff21de18d6 <unknown>
#20 0x55ff21df25a6 <unknown>
#21 0x7f522d29caa4 <unknown>
#22 0x7f522d329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_belgium_prod?event=eyJhY3Rpb24iOiJDaGFuZ2Ugb2YgbGFuZ3VhZ2UgcHJlZmVyZW5jZXMgLSBOTCIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJsYW5ndWFnZVByZWZlcmVuY2UiOiJOTCIsImdhQ2xpZW50SUQiOiIxNjM3MzY2MC4xNzQ2MzQyODYzIn0sImFub25JZCI6ImQzZGRkZGQ2NDMyZTczZDMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYmUvbmxfQkUvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0JFL25sL0MtS0xBU1NFL0xJTU9VU0lORSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiMjQxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiODYzNTcxODg0ODc1Mzc3MSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55ff21df375a <unknown>
#1 0x55ff218a64b0 <unknown>
#2 0x55ff2188cd86 <unknown>
#3 0x55ff2188b69a <unknown>
#4 0x55ff2188bdff <unknown>
#5 0x55ff2188bd54 <unknown>
#6 0x55ff218aa69f <unknown>
#7 0x55ff2194f92a <unknown>
#8 0x55ff2191d592 <unknown>
#9 0x55ff219435e0 <unknown>
#10 0x55ff2191d363 <unknown>
#11 0x55ff218e9d63 <unknown>
#12 0x55ff218ea9c1 <unknown>
#13 0x55ff21db8a6b <unknown>
#14 0x55ff21dbc951 <unknown>
#15 0x55ff21da0b62 <unknown>
#16 0x55ff21dbd4c4 <unknown>
#17 0x55ff21d8513f <unknown>
#18 0x55ff21de16f8 <unknown>
#19 0x55ff21de18d6 <unknown>
#20 0x55ff21df25a6 <unknown>
#21 0x7f522d29caa4 <unknown>
#22 0x7f522d329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_belgium_prod?event=eyJhY3Rpb24iOiJDaGFuZ2Ugb2YgbGFuZ3VhZ2UgcHJlZmVyZW5jZXMgLSBOTCIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJsYW5ndWFnZVByZWZlcmVuY2UiOiJOTCIsImdhQ2xpZW50SUQiOiIxNjM3MzY2MC4xNzQ2MzQyODYzIn0sImFub25JZCI6ImQzZGRkZGQ2NDMyZTczZDMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYmUvbmxfQkUvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0JFL25sL0MtS0xBU1NFL0xJTU9VU0lORSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiMjQxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTk5NzQyMTY4MDkxNjI0ODIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55ff21df375a <unknown>
#1 0x55ff218a64b0 <unknown>
#2 0x55ff2188cd86 <unknown>
#3 0x55ff2188b69a <unknown>
#4 0x55ff2188bdff <unknown>
#5 0x55ff2188bd54 <unknown>
#6 0x55ff218aa69f <unknown>
#7 0x55ff2194f92a <unknown>
#8 0x55ff2191d592 <unknown>
#9 0x55ff219435e0 <unknown>
#10 0x55ff2191d363 <unknown>
#11 0x55ff218e9d63 <unknown>
#12 0x55ff218ea9c1 <unknown>
#13 0x55ff21db8a6b <unknown>
#14 0x55ff21dbc951 <unknown>
#15 0x55ff21da0b62 <unknown>
#16 0x55ff21dbd4c4 <unknown>
#17 0x55ff21d8513f <unknown>
#18 0x55ff21de16f8 <unknown>
#19 0x55ff21de18d6 <unknown>
#20 0x55ff21df25a6 <unknown>
#21 0x7f522d29caa4 <unknown>
#22 0x7f522d329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:127 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Started' failed.