ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTM2NTc4NjE3NC4xNzQ2MzE1NTc1In0sImFub25JZCI6IjFiOTc0NDM3ZDA0ZDdjNTcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucHQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2VxZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjEwNTczOTY5Nzc1OTkzODMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x557fffcd875a <unknown>
#1 0x557fff78b4b0 <unknown>
#2 0x557fff771d86 <unknown>
#3 0x557fff77069a <unknown>
#4 0x557fff770dff <unknown>
#5 0x557fff770d54 <unknown>
#6 0x557fff78f69f <unknown>
#7 0x557fff83492a <unknown>
#8 0x557fff802592 <unknown>
#9 0x557fff8285e0 <unknown>
#10 0x557fff802363 <unknown>
#11 0x557fff7ced63 <unknown>
#12 0x557fff7cf9c1 <unknown>
#13 0x557fffc9da6b <unknown>
#14 0x557fffca1951 <unknown>
#15 0x557fffc85b62 <unknown>
#16 0x557fffca24c4 <unknown>
#17 0x557fffc6a13f <unknown>
#18 0x557fffcc66f8 <unknown>
#19 0x557fffcc68d6 <unknown>
#20 0x557fffcd75a6 <unknown>
#21 0x7f477d09caa4 <unknown>
#22 0x7f477d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJwdF9QVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzNjU3ODYxNzQuMTc0NjMxNTU3NSJ9LCJhbm9uSWQiOiIxYjk3NDQzN2QwNGQ3YzU3In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTQ2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTQ2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTAzOTk5OTM2NzE0MzAxMyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x557fffcd875a <unknown>
#1 0x557fff78b4b0 <unknown>
#2 0x557fff771d86 <unknown>
#3 0x557fff77069a <unknown>
#4 0x557fff770dff <unknown>
#5 0x557fff770d54 <unknown>
#6 0x557fff78f69f <unknown>
#7 0x557fff83492a <unknown>
#8 0x557fff802592 <unknown>
#9 0x557fff8285e0 <unknown>
#10 0x557fff802363 <unknown>
#11 0x557fff7ced63 <unknown>
#12 0x557fff7cf9c1 <unknown>
#13 0x557fffc9da6b <unknown>
#14 0x557fffca1951 <unknown>
#15 0x557fffc85b62 <unknown>
#16 0x557fffca24c4 <unknown>
#17 0x557fffc6a13f <unknown>
#18 0x557fffcc66f8 <unknown>
#19 0x557fffcc68d6 <unknown>
#20 0x557fffcd75a6 <unknown>
#21 0x7f477d09caa4 <unknown>
#22 0x7f477d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzNjU3ODYxNzQuMTc0NjMxNTU3NSJ9LCJhbm9uSWQiOiIxYjk3NDQzN2QwNGQ3YzU3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0MzgyODM3NDcyMDQ3MTEyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x557fffcd875a <unknown>
#1 0x557fff78b4b0 <unknown>
#2 0x557fff771d86 <unknown>
#3 0x557fff77069a <unknown>
#4 0x557fff770dff <unknown>
#5 0x557fff770d54 <unknown>
#6 0x557fff78f69f <unknown>
#7 0x557fff83492a <unknown>
#8 0x557fff802592 <unknown>
#9 0x557fff8285e0 <unknown>
#10 0x557fff802363 <unknown>
#11 0x557fff7ced63 <unknown>
#12 0x557fff7cf9c1 <unknown>
#13 0x557fffc9da6b <unknown>
#14 0x557fffca1951 <unknown>
#15 0x557fffc85b62 <unknown>
#16 0x557fffca24c4 <unknown>
#17 0x557fffc6a13f <unknown>
#18 0x557fffcc66f8 <unknown>
#19 0x557fffcc68d6 <unknown>
#20 0x557fffcd75a6 <unknown>
#21 0x7f477d09caa4 <unknown>
#22 0x7f477d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NCIsInZlaGljbGVCTSI6IjI5NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk0NiIsInRpbWVzdGFtcCI6MTc0NjMxNTU3OTY4NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzNjU3ODYxNzQuMTc0NjMxNTU3NSJ9LCJhbm9uSWQiOiIxYjk3NDQzN2QwNGQ3YzU3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjY0ODM3NTMzNDE2MjA1MzUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x557fffcd875a <unknown>
#1 0x557fff78b4b0 <unknown>
#2 0x557fff771d86 <unknown>
#3 0x557fff77069a <unknown>
#4 0x557fff770dff <unknown>
#5 0x557fff770d54 <unknown>
#6 0x557fff78f69f <unknown>
#7 0x557fff83492a <unknown>
#8 0x557fff802592 <unknown>
#9 0x557fff8285e0 <unknown>
#10 0x557fff802363 <unknown>
#11 0x557fff7ced63 <unknown>
#12 0x557fff7cf9c1 <unknown>
#13 0x557fffc9da6b <unknown>
#14 0x557fffca1951 <unknown>
#15 0x557fffc85b62 <unknown>
#16 0x557fffca24c4 <unknown>
#17 0x557fffc6a13f <unknown>
#18 0x557fffcc66f8 <unknown>
#19 0x557fffcc68d6 <unknown>
#20 0x557fffcd75a6 <unknown>
#21 0x7f477d09caa4 <unknown>
#22 0x7f477d129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/BFV1_attempt_2.png'