ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_slovakia_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJza19TSyIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnNrL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMDM2MDIuMTc0NjMxODIyNCJ9LCJhbm9uSWQiOiIyNjBmNGJmNDZjNmZjOGFmIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTQ2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTQ2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODUzMTk2MTMwODE4MTc0MSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562a4c45575a <unknown>
#1 0x562a4bf084b0 <unknown>
#2 0x562a4beeed86 <unknown>
#3 0x562a4beed69a <unknown>
#4 0x562a4beeddff <unknown>
#5 0x562a4beedd54 <unknown>
#6 0x562a4bf0c69f <unknown>
#7 0x562a4bfb192a <unknown>
#8 0x562a4bf7f592 <unknown>
#9 0x562a4bfa55e0 <unknown>
#10 0x562a4bf7f363 <unknown>
#11 0x562a4bf4bd63 <unknown>
#12 0x562a4bf4c9c1 <unknown>
#13 0x562a4c41aa6b <unknown>
#14 0x562a4c41e951 <unknown>
#15 0x562a4c402b62 <unknown>
#16 0x562a4c41f4c4 <unknown>
#17 0x562a4c3e713f <unknown>
#18 0x562a4c4436f8 <unknown>
#19 0x562a4c4438d6 <unknown>
#20 0x562a4c4545a6 <unknown>
#21 0x7f4452c9caa4 <unknown>
#22 0x7f4452d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_slovakia_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzAwMzYwMi4xNzQ2MzE4MjI0In0sImFub25JZCI6IjI2MGY0YmY0NmM2ZmM4YWYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouc2svcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2VxZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI1MDU0MDM1NTYxNjg5NzI1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562a4c45575a <unknown>
#1 0x562a4bf084b0 <unknown>
#2 0x562a4beeed86 <unknown>
#3 0x562a4beed69a <unknown>
#4 0x562a4beeddff <unknown>
#5 0x562a4beedd54 <unknown>
#6 0x562a4bf0c69f <unknown>
#7 0x562a4bfb192a <unknown>
#8 0x562a4bf7f592 <unknown>
#9 0x562a4bfa55e0 <unknown>
#10 0x562a4bf7f363 <unknown>
#11 0x562a4bf4bd63 <unknown>
#12 0x562a4bf4c9c1 <unknown>
#13 0x562a4c41aa6b <unknown>
#14 0x562a4c41e951 <unknown>
#15 0x562a4c402b62 <unknown>
#16 0x562a4c41f4c4 <unknown>
#17 0x562a4c3e713f <unknown>
#18 0x562a4c4436f8 <unknown>
#19 0x562a4c4438d6 <unknown>
#20 0x562a4c4545a6 <unknown>
#21 0x7f4452c9caa4 <unknown>
#22 0x7f4452d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_slovakia_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMDM2MDIuMTc0NjMxODIyNCJ9LCJhbm9uSWQiOiIyNjBmNGJmNDZjNmZjOGFmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnNrL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxOTk1NDE4NDgzODA5MDYwNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562a4c45575a <unknown>
#1 0x562a4bf084b0 <unknown>
#2 0x562a4beeed86 <unknown>
#3 0x562a4beed69a <unknown>
#4 0x562a4beeddff <unknown>
#5 0x562a4beedd54 <unknown>
#6 0x562a4bf0c69f <unknown>
#7 0x562a4bfb192a <unknown>
#8 0x562a4bf7f592 <unknown>
#9 0x562a4bfa55e0 <unknown>
#10 0x562a4bf7f363 <unknown>
#11 0x562a4bf4bd63 <unknown>
#12 0x562a4bf4c9c1 <unknown>
#13 0x562a4c41aa6b <unknown>
#14 0x562a4c41e951 <unknown>
#15 0x562a4c402b62 <unknown>
#16 0x562a4c41f4c4 <unknown>
#17 0x562a4c3e713f <unknown>
#18 0x562a4c4436f8 <unknown>
#19 0x562a4c4438d6 <unknown>
#20 0x562a4c4545a6 <unknown>
#21 0x7f4452c9caa4 <unknown>
#22 0x7f4452d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_slovakia_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnNrL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NCIsInZlaGljbGVCTSI6IjI5NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk0NiIsInRpbWVzdGFtcCI6MTc0NjMxODIyOTc1MiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMDM2MDIuMTc0NjMxODIyNCJ9LCJhbm9uSWQiOiIyNjBmNGJmNDZjNmZjOGFmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnNrL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjI3NjkyOTYzODUwNTA5NzY2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562a4c45575a <unknown>
#1 0x562a4bf084b0 <unknown>
#2 0x562a4beeed86 <unknown>
#3 0x562a4beed69a <unknown>
#4 0x562a4beeddff <unknown>
#5 0x562a4beedd54 <unknown>
#6 0x562a4bf0c69f <unknown>
#7 0x562a4bfb192a <unknown>
#8 0x562a4bf7f592 <unknown>
#9 0x562a4bfa55e0 <unknown>
#10 0x562a4bf7f363 <unknown>
#11 0x562a4bf4bd63 <unknown>
#12 0x562a4bf4c9c1 <unknown>
#13 0x562a4c41aa6b <unknown>
#14 0x562a4c41e951 <unknown>
#15 0x562a4c402b62 <unknown>
#16 0x562a4c41f4c4 <unknown>
#17 0x562a4c3e713f <unknown>
#18 0x562a4c4436f8 <unknown>
#19 0x562a4c4438d6 <unknown>
#20 0x562a4c4545a6 <unknown>
#21 0x7f4452c9caa4 <unknown>
#22 0x7f4452d29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:127 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/BFV1_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'BFV1' failed.