ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNDM1NjQwODkzLjE3NDYzMTYxOTQifSwiYW5vbklkIjoiN2Q0ZWRjMWU1MGQ4YjQzMSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5wdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDcxNzQzMjEzNDAyMjA5OCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562e81d7d75a <unknown>
#1 0x562e818304b0 <unknown>
#2 0x562e81816d86 <unknown>
#3 0x562e8181569a <unknown>
#4 0x562e81815dff <unknown>
#5 0x562e81815d54 <unknown>
#6 0x562e8183469f <unknown>
#7 0x562e818d992a <unknown>
#8 0x562e818a7592 <unknown>
#9 0x562e818cd5e0 <unknown>
#10 0x562e818a7363 <unknown>
#11 0x562e81873d63 <unknown>
#12 0x562e818749c1 <unknown>
#13 0x562e81d42a6b <unknown>
#14 0x562e81d46951 <unknown>
#15 0x562e81d2ab62 <unknown>
#16 0x562e81d474c4 <unknown>
#17 0x562e81d0f13f <unknown>
#18 0x562e81d6b6f8 <unknown>
#19 0x562e81d6b8d6 <unknown>
#20 0x562e81d7c5a6 <unknown>
#21 0x7fc09129caa4 <unknown>
#22 0x7fc091329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNjc5IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJwdF9QVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbHMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjEifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjQzNTY0MDg5My4xNzQ2MzE2MTk0In0sImFub25JZCI6IjdkNGVkYzFlNTBkOGI0MzEifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjE2NzkiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjE2NzkiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0NTI1NDQxNTI4NTEwMzE1NiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562e81d7d75a <unknown>
#1 0x562e818304b0 <unknown>
#2 0x562e81816d86 <unknown>
#3 0x562e8181569a <unknown>
#4 0x562e81815dff <unknown>
#5 0x562e81815d54 <unknown>
#6 0x562e8183469f <unknown>
#7 0x562e818d992a <unknown>
#8 0x562e818a7592 <unknown>
#9 0x562e818cd5e0 <unknown>
#10 0x562e818a7363 <unknown>
#11 0x562e81873d63 <unknown>
#12 0x562e818749c1 <unknown>
#13 0x562e81d42a6b <unknown>
#14 0x562e81d46951 <unknown>
#15 0x562e81d2ab62 <unknown>
#16 0x562e81d474c4 <unknown>
#17 0x562e81d0f13f <unknown>
#18 0x562e81d6b6f8 <unknown>
#19 0x562e81d6b8d6 <unknown>
#20 0x562e81d7c5a6 <unknown>
#21 0x7fc09129caa4 <unknown>
#22 0x7fc091329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjQzNTY0MDg5My4xNzQ2MzE2MTk0In0sImFub25JZCI6IjdkNGVkYzFlNTBkOGI0MzEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucHQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dscy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjIwNDc5Mjg5NzE3NTcyMjEzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562e81d7d75a <unknown>
#1 0x562e818304b0 <unknown>
#2 0x562e81816d86 <unknown>
#3 0x562e8181569a <unknown>
#4 0x562e81815dff <unknown>
#5 0x562e81815d54 <unknown>
#6 0x562e8183469f <unknown>
#7 0x562e818d992a <unknown>
#8 0x562e818a7592 <unknown>
#9 0x562e818cd5e0 <unknown>
#10 0x562e818a7363 <unknown>
#11 0x562e81873d63 <unknown>
#12 0x562e818749c1 <unknown>
#13 0x562e81d42a6b <unknown>
#14 0x562e81d46951 <unknown>
#15 0x562e81d2ab62 <unknown>
#16 0x562e81d474c4 <unknown>
#17 0x562e81d0f13f <unknown>
#18 0x562e81d6b6f8 <unknown>
#19 0x562e81d6b8d6 <unknown>
#20 0x562e81d7c5a6 <unknown>
#21 0x7fc09129caa4 <unknown>
#22 0x7fc091329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_portugal_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnB0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbHMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDE2Ny1mbCIsInZlaGljbGVCTSI6IjE2NzkiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMTY3OSIsInRpbWVzdGFtcCI6MTc0NjMxNjIwMzIwOCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjQzNTY0MDg5My4xNzQ2MzE2MTk0In0sImFub25JZCI6IjdkNGVkYzFlNTBkOGI0MzEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucHQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dscy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiODg1MTM0NzM4NDU4OTM3OSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x562e81d7d75a <unknown>
#1 0x562e818304b0 <unknown>
#2 0x562e81816d86 <unknown>
#3 0x562e8181569a <unknown>
#4 0x562e81815dff <unknown>
#5 0x562e81815d54 <unknown>
#6 0x562e8183469f <unknown>
#7 0x562e818d992a <unknown>
#8 0x562e818a7592 <unknown>
#9 0x562e818cd5e0 <unknown>
#10 0x562e818a7363 <unknown>
#11 0x562e81873d63 <unknown>
#12 0x562e818749c1 <unknown>
#13 0x562e81d42a6b <unknown>
#14 0x562e81d46951 <unknown>
#15 0x562e81d2ab62 <unknown>
#16 0x562e81d474c4 <unknown>
#17 0x562e81d0f13f <unknown>
#18 0x562e81d6b6f8 <unknown>
#19 0x562e81d6b8d6 <unknown>
#20 0x562e81d7c5a6 <unknown>
#21 0x7fc09129caa4 <unknown>
#22 0x7fc091329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/BFV1_attempt_2.png'