ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6bnVsbCwic291cmNlIjp7InBhZ2VUeXBlIjoicHJvZHVjdF9pbmZvcm1hdGlvbiIsImNvbnRlbnRab25lcyI6WyJwaV9wb3B1cCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmRlL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjM0MSJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYW5vbklkIjoiYjE1MTYxMjA2ZDY3MzJhNiJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzOTgyMTA3MDEzOTE2ODM4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x556a0594c7fa <unknown>
#1 0x556a053f0e90 <unknown>
#2 0x556a053d8156 <unknown>
#3 0x556a053d6a6a <unknown>
#4 0x556a053d71cf <unknown>
#5 0x556a053d7124 <unknown>
#6 0x556a053f511f <unknown>
#7 0x556a0549a3ca <unknown>
#8 0x556a05468242 <unknown>
#9 0x556a0548e135 <unknown>
#10 0x556a05468013 <unknown>
#11 0x556a05434b3b <unknown>
#12 0x556a054357a1 <unknown>
#13 0x556a05911b9b <unknown>
#14 0x556a05915a8a <unknown>
#15 0x556a058f9912 <unknown>
#16 0x556a05916604 <unknown>
#17 0x556a058de74f <unknown>
#18 0x556a0593a678 <unknown>
#19 0x556a0593a856 <unknown>
#20 0x556a0594b666 <unknown>
#21 0x7f918449caa4 <unknown>
#22 0x7f9184529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmRlL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjM0MSIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6ImIxNTE2MTIwNmQ2NzMyYTYifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzMDc4ODk2NTUwNzI4OTc2NyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x556a0594c7fa <unknown>
#1 0x556a053f0e90 <unknown>
#2 0x556a053d8156 <unknown>
#3 0x556a053d6a6a <unknown>
#4 0x556a053d71cf <unknown>
#5 0x556a053d7124 <unknown>
#6 0x556a053f511f <unknown>
#7 0x556a0549a3ca <unknown>
#8 0x556a05468242 <unknown>
#9 0x556a0548e135 <unknown>
#10 0x556a05468013 <unknown>
#11 0x556a05434b3b <unknown>
#12 0x556a054357a1 <unknown>
#13 0x556a05911b9b <unknown>
#14 0x556a05915a8a <unknown>
#15 0x556a058f9912 <unknown>
#16 0x556a05916604 <unknown>
#17 0x556a058de74f <unknown>
#18 0x556a0593a678 <unknown>
#19 0x556a0593a856 <unknown>
#20 0x556a0594b666 <unknown>
#21 0x7f918449caa4 <unknown>
#22 0x7f9184529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJCYXVtdXN0ZXJTaG9ydCI6eyJfaWQiOiIyNTQ2IiwibmFtZSI6IjI1NDYiLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmRlL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJyZWxhdGVkQ2F0YWxvZ09iamVjdHMiOnsiQnJhbmQiOlsiZ2xjLWNsYXNzIl0sIkJvZHlUeXBlIjpbIm9mZnJvYWRlciJdLCJNb2RlbFNlcmllcyI6WyJ4MjU0Il0sIlN1YkJyYW5kIjpbIiJdfX19LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5kZS9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjL292ZXJ2aWV3Lmh0bWw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiIzNDEiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiJiMTUxNjEyMDZkNjczMmE2In0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzIyNTQ4NDQzMjI5MDc0NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x556a0594c7fa <unknown>
#1 0x556a053f0e90 <unknown>
#2 0x556a053d8156 <unknown>
#3 0x556a053d6a6a <unknown>
#4 0x556a053d71cf <unknown>
#5 0x556a053d7124 <unknown>
#6 0x556a053f511f <unknown>
#7 0x556a0549a3ca <unknown>
#8 0x556a05468242 <unknown>
#9 0x556a0548e135 <unknown>
#10 0x556a05468013 <unknown>
#11 0x556a05434b3b <unknown>
#12 0x556a054357a1 <unknown>
#13 0x556a05911b9b <unknown>
#14 0x556a05915a8a <unknown>
#15 0x556a058f9912 <unknown>
#16 0x556a05916604 <unknown>
#17 0x556a058de74f <unknown>
#18 0x556a0593a678 <unknown>
#19 0x556a0593a856 <unknown>
#20 0x556a0594b666 <unknown>
#21 0x7f918449caa4 <unknown>
#22 0x7f9184529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_germany_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5kZS9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjL292ZXJ2aWV3Lmh0bWw%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiIzNDEiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiJiMTUxNjEyMDZkNjczMmE2In0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiMDgwNzcxNTM0Njc2NzYyOSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x556a0594c7fa <unknown>
#1 0x556a053f0e90 <unknown>
#2 0x556a053d8156 <unknown>
#3 0x556a053d6a6a <unknown>
#4 0x556a053d71cf <unknown>
#5 0x556a053d7124 <unknown>
#6 0x556a053f511f <unknown>
#7 0x556a0549a3ca <unknown>
#8 0x556a05468242 <unknown>
#9 0x556a0548e135 <unknown>
#10 0x556a05468013 <unknown>
#11 0x556a05434b3b <unknown>
#12 0x556a054357a1 <unknown>
#13 0x556a05911b9b <unknown>
#14 0x556a05915a8a <unknown>
#15 0x556a058f9912 <unknown>
#16 0x556a05916604 <unknown>
#17 0x556a058de74f <unknown>
#18 0x556a0593a678 <unknown>
#19 0x556a0593a856 <unknown>
#20 0x556a0594b666 <unknown>
#21 0x7f918449caa4 <unknown>
#22 0x7f9184529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/BFV1_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: