ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTMyOTE3NDc2MC4xNzQ3MTMxNTA2In0sImFub25JZCI6IjBhMzljNzA5YTkyOGY3NDkifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoubHUvZnIvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2NsYS1lbGVjdHJpYy9vdmVydmlldy5odG1sP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTUiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMzM2NTUzNDYwMjMzMDg0MiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55d3d8f0c7fa <unknown>
#1 0x55d3d89b0e90 <unknown>
#2 0x55d3d8998156 <unknown>
#3 0x55d3d8996a6a <unknown>
#4 0x55d3d89971cf <unknown>
#5 0x55d3d8997124 <unknown>
#6 0x55d3d89b511f <unknown>
#7 0x55d3d8a5a3ca <unknown>
#8 0x55d3d8a28242 <unknown>
#9 0x55d3d8a4e135 <unknown>
#10 0x55d3d8a28013 <unknown>
#11 0x55d3d89f4b3b <unknown>
#12 0x55d3d89f57a1 <unknown>
#13 0x55d3d8ed1b9b <unknown>
#14 0x55d3d8ed5a8a <unknown>
#15 0x55d3d8eb9912 <unknown>
#16 0x55d3d8ed6604 <unknown>
#17 0x55d3d8e9e74f <unknown>
#18 0x55d3d8efa678 <unknown>
#19 0x55d3d8efa856 <unknown>
#20 0x55d3d8f0b666 <unknown>
#21 0x7f37d8e9caa4 <unknown>
#22 0x7f37d8f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNzQzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJmcl9MVSIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2ZyL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9jbGEtZWxlY3RyaWMvb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMzI5MTc0NzYwLjE3NDcxMzE1MDYifSwiYW5vbklkIjoiMGEzOWM3MDlhOTI4Zjc0OSJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTc0MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTc0MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjY3OTg1ODg1MDIyOTg4NDMifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55d3d8f0c7fa <unknown>
#1 0x55d3d89b0e90 <unknown>
#2 0x55d3d8998156 <unknown>
#3 0x55d3d8996a6a <unknown>
#4 0x55d3d89971cf <unknown>
#5 0x55d3d8997124 <unknown>
#6 0x55d3d89b511f <unknown>
#7 0x55d3d8a5a3ca <unknown>
#8 0x55d3d8a28242 <unknown>
#9 0x55d3d8a4e135 <unknown>
#10 0x55d3d8a28013 <unknown>
#11 0x55d3d89f4b3b <unknown>
#12 0x55d3d89f57a1 <unknown>
#13 0x55d3d8ed1b9b <unknown>
#14 0x55d3d8ed5a8a <unknown>
#15 0x55d3d8eb9912 <unknown>
#16 0x55d3d8ed6604 <unknown>
#17 0x55d3d8e9e74f <unknown>
#18 0x55d3d8efa678 <unknown>
#19 0x55d3d8efa856 <unknown>
#20 0x55d3d8f0b666 <unknown>
#21 0x7f37d8e9caa4 <unknown>
#22 0x7f37d8f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzMjkxNzQ3NjAuMTc0NzEzMTUwNiJ9LCJhbm9uSWQiOiIwYTM5YzcwOWE5MjhmNzQ5In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2ZyL3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9jbGEtZWxlY3RyaWMvb3ZlcnZpZXcuaHRtbD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiMTk3ODU4MTg0NjY1MDIxNDciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55d3d8f0c7fa <unknown>
#1 0x55d3d89b0e90 <unknown>
#2 0x55d3d8998156 <unknown>
#3 0x55d3d8996a6a <unknown>
#4 0x55d3d89971cf <unknown>
#5 0x55d3d8997124 <unknown>
#6 0x55d3d89b511f <unknown>
#7 0x55d3d8a5a3ca <unknown>
#8 0x55d3d8a28242 <unknown>
#9 0x55d3d8a4e135 <unknown>
#10 0x55d3d8a28013 <unknown>
#11 0x55d3d89f4b3b <unknown>
#12 0x55d3d89f57a1 <unknown>
#13 0x55d3d8ed1b9b <unknown>
#14 0x55d3d8ed5a8a <unknown>
#15 0x55d3d8eb9912 <unknown>
#16 0x55d3d8ed6604 <unknown>
#17 0x55d3d8e9e74f <unknown>
#18 0x55d3d8efa678 <unknown>
#19 0x55d3d8efa856 <unknown>
#20 0x55d3d8f0b666 <unknown>
#21 0x7f37d8e9caa4 <unknown>
#22 0x7f37d8f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/BFV1_attempt_2.png'